frontend:
  containers:
    image: neondb-kafka-frontend:latest

  envVars:
    BASE_URL: localhost

  ingress:
    ingressClassName: kong
    host: null

webAPI:
  containers:
    image: neondb-kafka-web-api:latest

  envVars:
    POSTGRES_USER: jeff-vincent
    POSTGRES_HOST: ep-lucky-cake-429261.us-west-2.aws.neon.tech
    POSTGRES_DB: analytics

dataService:
  containers:
    image: neondb-kafka-data:latest

  envVars:
    KAFKA_HOST: my-kafka

worker:
  containers:
    image: neondb-kafka-worker:latest

  envVars:
    POSTGRES_USER: jeff-vincent
    POSTGRES_HOST: ep-lucky-cake-429261.us-west-2.aws.neon.tech
    POSTGRES_DB: analytics
    KAFKA_HOST: my-kafka-headless
